// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huqmllnvhsybghsirdaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1cW1sbG52aHN5Ymdoc2lyZGFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzIxNjEsImV4cCI6MjA1OTgwODE2MX0.FikiA9XBWdmd-kEJQoSvBi40-Ss_u06TmRr0RtqxCqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);